apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ya6a8bim9-python 
  janus-idp.io/tekton: ya6a8bim9-python
  backstage.io/kubernetes-id: ya6a8bim9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ya6a8bim9-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml