apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ya6a8bim9-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ya6a8bim9-python 
  name: ya6a8bim9-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ya6a8bim9-python 
